[Login]
SleepOperation=hybrid-sleep suspend
HandlePowerKey=hybrid-sleep suspend
HandlePowerKeyLongPress=ignore
HandleRebootKey=hybrid-sleep suspend
HandleRebootKeyLongPress=ignore
HandleSuspendKey=hybrid-sleep suspend
HandleSuspendKeyLongPress=ignore
HandleHibernateKey=hybrid-sleep suspend
HandleHibernateKeyLongPress=ignore
HandleLidSwitch=hybrid-sleep suspend
HandleLidSwitchExternalPower=hybrid-sleep suspend
HandleLidSwitchDocked=hybrid-sleep suspend
PowerKeyIgnoreInhibited=yes
SuspendKeyIgnoreInhibited=yes
HibernateKeyIgnoreInhibited=yes
LidSwitchIgnoreInhibited=yes
RebootKeyIgnoreInhibited=yes